
package br.univel.produto;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProdutoWBS", targetNamespace = "http://webservices.univel.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProdutoWBS {


    /**
     * 
     * @param idProduto
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Ler_Produto")
    @WebResult(name = "Produto", targetNamespace = "")
    @RequestWrapper(localName = "Ler_Produto", targetNamespace = "http://webservices.univel.br/", className = "br.univel.produto.LerProduto")
    @ResponseWrapper(localName = "Ler_ProdutoResponse", targetNamespace = "http://webservices.univel.br/", className = "br.univel.produto.LerProdutoResponse")
    public String lerProduto(
        @WebParam(name = "IdProduto", targetNamespace = "")
        Long idProduto);

    /**
     * 
     * @param preco
     * @param codBarra
     * @param descricao
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Cadastrar_Produto")
    @WebResult(name = "Status_Cad_Produto", targetNamespace = "")
    @RequestWrapper(localName = "Cadastrar_Produto", targetNamespace = "http://webservices.univel.br/", className = "br.univel.produto.CadastrarProduto")
    @ResponseWrapper(localName = "Cadastrar_ProdutoResponse", targetNamespace = "http://webservices.univel.br/", className = "br.univel.produto.CadastrarProdutoResponse")
    public String cadastrarProduto(
        @WebParam(name = "Cod_barra", targetNamespace = "")
        String codBarra,
        @WebParam(name = "Descricao", targetNamespace = "")
        String descricao,
        @WebParam(name = "Preco", targetNamespace = "")
        BigDecimal preco);

    /**
     * 
     * @param preco
     * @param idProduto
     * @param codBarra
     * @param descricao
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Atualizar_Produto")
    @WebResult(name = "Produto_Atualizado", targetNamespace = "")
    @RequestWrapper(localName = "Atualizar_Produto", targetNamespace = "http://webservices.univel.br/", className = "br.univel.produto.AtualizarProduto")
    @ResponseWrapper(localName = "Atualizar_ProdutoResponse", targetNamespace = "http://webservices.univel.br/", className = "br.univel.produto.AtualizarProdutoResponse")
    public String atualizarProduto(
        @WebParam(name = "IdProduto", targetNamespace = "")
        Long idProduto,
        @WebParam(name = "Cod_barra", targetNamespace = "")
        String codBarra,
        @WebParam(name = "Descricao", targetNamespace = "")
        String descricao,
        @WebParam(name = "Preco", targetNamespace = "")
        BigDecimal preco);

    /**
     * 
     * @param idProduto
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Excluir_Produto")
    @WebResult(name = "Status_Produto", targetNamespace = "")
    @RequestWrapper(localName = "Excluir_Produto", targetNamespace = "http://webservices.univel.br/", className = "br.univel.produto.ExcluirProduto")
    @ResponseWrapper(localName = "Excluir_ProdutoResponse", targetNamespace = "http://webservices.univel.br/", className = "br.univel.produto.ExcluirProdutoResponse")
    public String excluirProduto(
        @WebParam(name = "IdProduto", targetNamespace = "")
        Long idProduto);

}
