
package br.univel.venda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaWBS", targetNamespace = "http://webservices.univel.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VendaWBS {


    /**
     * 
     * @param numNota
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "status_Venda", targetNamespace = "")
    @RequestWrapper(localName = "vender", targetNamespace = "http://webservices.univel.br/", className = "br.univel.venda.Vender")
    @ResponseWrapper(localName = "venderResponse", targetNamespace = "http://webservices.univel.br/", className = "br.univel.venda.VenderResponse")
    public String vender(
        @WebParam(name = "num_Nota", targetNamespace = "")
        int numNota);

}
