
package br.univel.entrega;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EntregaWBSService", targetNamespace = "http://webservices.univel.br/", wsdlLocation = "http://localhost:8085/lab141457/EntregaWBS?wsdl")
public class EntregaWBSService
    extends Service
{

    private final static URL ENTREGAWBSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENTREGAWBSSERVICE_EXCEPTION;
    private final static QName ENTREGAWBSSERVICE_QNAME = new QName("http://webservices.univel.br/", "EntregaWBSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/lab141457/EntregaWBS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTREGAWBSSERVICE_WSDL_LOCATION = url;
        ENTREGAWBSSERVICE_EXCEPTION = e;
    }

    public EntregaWBSService() {
        super(__getWsdlLocation(), ENTREGAWBSSERVICE_QNAME);
    }

    public EntregaWBSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTREGAWBSSERVICE_QNAME, features);
    }

    public EntregaWBSService(URL wsdlLocation) {
        super(wsdlLocation, ENTREGAWBSSERVICE_QNAME);
    }

    public EntregaWBSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTREGAWBSSERVICE_QNAME, features);
    }

    public EntregaWBSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntregaWBSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EntregaWBS
     */
    @WebEndpoint(name = "EntregaWBSPort")
    public EntregaWBS getEntregaWBSPort() {
        return super.getPort(new QName("http://webservices.univel.br/", "EntregaWBSPort"), EntregaWBS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntregaWBS
     */
    @WebEndpoint(name = "EntregaWBSPort")
    public EntregaWBS getEntregaWBSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.univel.br/", "EntregaWBSPort"), EntregaWBS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTREGAWBSSERVICE_EXCEPTION!= null) {
            throw ENTREGAWBSSERVICE_EXCEPTION;
        }
        return ENTREGAWBSSERVICE_WSDL_LOCATION;
    }

}
